### ISSUE TITLE
API cleanup for more idiomatic rust

### ISSUE THREAD

**Issue by sgeisler** [clarkmoody/rust-bech32#5]
#4 implemented `FromStr` for `Bech32`. Since it's a API-breaking change I want to collect more API cleanup ideas that can be batched in one release.

- [x] implement `FromStr` #4
- [x] implement `Display`, which automatically implements `ToString`. This requires the members ob `Bech32` to become private and a constructor that checks the validity of the data to encode (so `to_string` can never return `Err(…)`). #6 
- [x] implement `convert_bits` [add-convert-bits](https://github.com/clarkmoody/rust-bech32/tree/add-convert-bits)
- [x] final cleanup #10

**Comment by clarkmoody** [comment]
Updated code in branch [add-convert-bits](https://github.com/clarkmoody/rust-bech32/tree/add-convert-bits), exposes `convert_bits` function from [rust-bech32-bitcoin](https://github.com/clarkmoody/rust-bech32-bitcoin).

**Comment by sgeisler** [comment]
@clarkmoody what do you think about defining a `u5` type to avoid redundant range checks? It could be a wrapper around a `u8` with a checking `new` and an `as_u8` function. 

Right now it's usefulness would be limited but it could for example enable a `set_data` function which can't fail.

**Comment by clarkmoody** [comment]
What would the ergonomics of the custom `u5` type be like?

**Comment by sgeisler** [comment]
I don't think ergonomics are a big problem. The `u5` data type isn't intended to be used with arithmetic operators. You basically create objects with the `new(u8) -> Result<u5, ()>` function, pass them around and if you want to use the underlying value you do this through the `as_u8(&self) -> &u8` or `into_u8(self) -> u8` functions.

**Comment by apoelstra** [comment]
Is there anything I can do to help with this? I would really like a new API release so that I can avoid converting strings to `String` before parsing them.

**Comment by clarkmoody** [comment]
Check out #9, as it seems to be blocking this PR.

**Comment by sgeisler** [comment]
Please don't close this bug yet, I will open a final cleanup PR as described in #9.

**Comment by sgeisler** [comment]
I don't know if this is intended, but the `Error` struct does not implement `Clone` or `Copy` (I think both would be possible). Should I just add a derive for both?

**Comment by sgeisler** [comment]
Since v0.3.1 was published on crates.io yesterday I think we can close this issue.
